# Generated by Django 5.1.5 on 2025-05-17 06:04

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        error_messages={"unique": "A store with this name already exists."},
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("store_description", models.TextField()),
                (
                    "store_url",
                    models.CharField(
                        error_messages={"unique": "A store with this URL already exists."},
                        max_length=75,
                        unique=True,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("store_logo", models.ImageField(blank=True, null=True, upload_to="store_logos/")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
