# Generated by Django 5.0.3 on 2024-08-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_alter_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
