# Generated by Django 5.0.3 on 2024-08-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_store_contact_email_store_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
