# Generated by Django 5.0.3 on 2024-08-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0005_alter_store_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='description',
            new_name='store_description',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='url',
            new_name='store_url',
        ),
    ]
