# Generated by Django 5.1.5 on 2025-02-20 05:19

import Stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Stores", "0007_store_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.CharField(
                default=Stores.models.generate_unique_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
