# Generated by Django 5.0.3 on 2024-04-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Stores', '0003_alter_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stock_notifications',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
        ),
    ]
