# Generated by Django 5.0.3 on 2024-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_customuser_date_of_birth_customuser_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='notes',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
