# Generated by Django 5.0.3 on 2024-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_customuser_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_phone_number_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
