# Generated by Django 5.0.3 on 2024-09-29 03:45

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_customuser_country_phone_number_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.CustomUser.user_profile_picture_path),
        ),
    ]
