# Generated by Django 5.0.3 on 2025-01-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
    ]
