# Generated by Django 5.1.5 on 2025-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0010_remove_customuser_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
