# Generated by Django 5.1.5 on 2025-05-17 06:04

import Products.models
import core.helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Orders", "0001_initial"),
        ("Stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        error_messages={"unique": "Category with this name already exists"},
                        max_length=45,
                        unique=True,
                    ),
                ),
                ("category_description", models.TextField(blank=True, null=True)),
                ("top_subcategories_products", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InitialProductState",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_name", models.CharField(blank=True, max_length=255, null=True)),
                ("product_description", models.TextField(blank=True, null=True)),
                ("properties", models.JSONField(blank=True, default=dict, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("draft", models.BooleanField(default=False)),
                ("prices", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_created_at", models.DateTimeField()),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Stores.store",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InitialProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="product_images/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("s3_key", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initial_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.initialproductstate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        error_messages={"unique": "Product with this name already exists"},
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("product_description", models.TextField(blank=True, null=True)),
                ("properties", models.JSONField(blank=True, default=dict, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("draft", models.BooleanField(default=False)),
                ("prices", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Stores.store",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("edit_product", "Can edit product"),
                    ("view_product_statistics", "Can view product statistics"),
                ],
            },
        ),
        migrations.AddField(
            model_name="initialproductstate",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Products.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=Products.models.product_image_upload_path
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("s3_key", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Products.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductInOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Products.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSubcategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "subcategory_name",
                    models.CharField(
                        error_messages={"unique": "Subcategory with this name already exists"},
                        max_length=45,
                        unique=True,
                    ),
                ),
                ("subcategory_description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Products.productcategory"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.productsubcategory",
            ),
        ),
        migrations.AddField(
            model_name="initialproductstate",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.productsubcategory",
            ),
        ),
        migrations.CreateModel(
            name="ProductTopSubcategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.helpers.generate_unique_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.productsubcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
