# Generated by Django 5.0.3 on 2024-04-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_details'),
        ('Stores', '0002_remove_store_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Stores.store'),
            preserve_default=False,
        ),
    ]
