# Generated by Django 5.0.3 on 2024-04-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_productinorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
