# Generated by Django 5.0.3 on 2024-04-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_productcategory_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
