# Generated by Django 5.0.3 on 2024-10-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_product_category_productsubcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='description',
            new_name='subcategory_description',
        ),
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='name',
            new_name='subcategory_name',
        ),
    ]
