# Generated by Django 5.0.3 on 2024-10-04 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_rename_description_productcategory_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTopSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_1', to='Products.productsubcategory')),
                ('subcategory_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_2', to='Products.productsubcategory')),
                ('subcategory_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_3', to='Products.productsubcategory')),
                ('subcategory_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_4', to='Products.productsubcategory')),
                ('subcategory_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_5', to='Products.productsubcategory')),
                ('subcategory_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_6', to='Products.productsubcategory')),
            ],
        ),
    ]
