# Generated by Django 5.0.3 on 2024-10-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_producttopsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttopsubcategory',
            old_name='subcategory_1',
            new_name='top_subcategory_1',
        ),
        migrations.RenameField(
            model_name='producttopsubcategory',
            old_name='subcategory_2',
            new_name='top_subcategory_2',
        ),
        migrations.RenameField(
            model_name='producttopsubcategory',
            old_name='subcategory_3',
            new_name='top_subcategory_3',
        ),
        migrations.RenameField(
            model_name='producttopsubcategory',
            old_name='subcategory_4',
            new_name='top_subcategory_4',
        ),
        migrations.RenameField(
            model_name='producttopsubcategory',
            old_name='subcategory_5',
            new_name='top_subcategory_5',
        ),
        migrations.RenameField(
            model_name='producttopsubcategory',
            old_name='subcategory_6',
            new_name='top_subcategory_6',
        ),
    ]
