# Generated by Django 5.0.3 on 2024-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_rename_subcategory_1_producttopsubcategory_top_subcategory_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='top_subcategory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductTopSubCategory',
        ),
    ]
