# Generated by Django 5.0.3 on 2024-10-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_productcategory_top_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='top_subcategory',
            new_name='top_subcategories',
        ),
    ]
