# Generated by Django 5.0.3 on 2024-10-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_rename_top_subcategory_productcategory_top_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='top_subcategories',
            field=models.JSONField(default=list),
        ),
    ]
