# Generated by Django 5.0.3 on 2024-11-07 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_remove_productcategory_top_subcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory')),
            ],
        ),
    ]
