# Generated by Django 5.0.3 on 2024-11-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_rename_topsubcategory_producttopsubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttopsubcategory',
            options={'ordering': ['order']},
        ),
    ]
