# Generated by Django 5.0.3 on 2024-12-05 06:35

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=Products.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
