# Generated by Django 5.0.3 on 2024-12-05 06:52

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.CharField(default=Products.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='id',
            field=models.CharField(default=Products.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='producttopsubcategory',
            name='id',
            field=models.CharField(default=Products.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
