# Generated by Django 5.0.3 on 2024-12-13 02:19

import Products.models
import django.db.models.deletion
from django.db import migrations, models
from core.helpers import generate_unique_id


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_remove_product_details_product_properties'),
        ('Stores', '0007_store_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InitialProductState',
            fields=[
                ('id', models.CharField(default=generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('draft', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stores.store')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsubcategory')),
            ],
        ),
    ]
