# Generated by Django 5.0.3 on 2024-12-13 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_remove_product_quantity_alter_product_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.initialproductstate')),
            ],
        ),
    ]
