# Generated by Django 5.0.3 on 2024-12-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_initialproductimage_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialproductstate',
            name='created_on',
        ),
    ]
