# Generated by Django 5.0.3 on 2024-12-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_remove_initialproductstate_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialproductimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
