# Generated by Django 5.0.3 on 2024-12-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_initialproductimage_order_productimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialproductimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
