# Generated by Django 5.0.3 on 2024-12-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_initialproductimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialproductimage',
            name='to_be_deleted',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='to_be_deleted',
        ),
    ]
