# Generated by Django 5.0.3 on 2024-12-20 04:38

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0034_remove_initialproductimage_to_be_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.CharField(default=Products.models.generate_unique_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
