# Generated by Django 5.0.3 on 2025-01-04 06:56

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_rename_created_on_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialproductstate',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product_image_upload_path),
        ),
    ]
