# Generated by Django 5.0.3 on 2025-01-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0037_rename_sub_category_initialproductstate_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialproductstate',
            old_name='description',
            new_name='product_escription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
    ]
