# Generated by Django 5.0.3 on 2025-01-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0038_rename_description_initialproductstate_product_escription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialproductstate',
            old_name='product_escription',
            new_name='product_description',
        ),
    ]
