# Generated by Django 5.0.3 on 2025-01-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0039_rename_product_escription_initialproductstate_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('edit_product', 'Can edit product'), ('view_product_statistics', 'Can view product statistics')]},
        ),
    ]
