# Generated by Django 5.0.3 on 2025-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialproductstate',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
