# Generated by Django 5.1.5 on 2025-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0042_rename_product_initialproductimage_initial_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "Product with this name already exists"},
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
