name: Deploy to EC2

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/project_files/Plataforma-De-Vendas/Plataforma_de_Vendas
            git pull origin main
            conda activate conda_env

            echo "Checking for migration conflicts..."
            MIGRATION_OUTPUT=$(python manage.py makemigrations --dry-run 2>&1)
            if echo "$MIGRATION_OUTPUT" | grep -q "conflicting"; then
              echo "Migration conflict detected. Merging migrations..."
              python manage.py makemigrations --merge
            else
              echo "No migration conflicts detected..."
            fi

            python manage.py migrate
            python manage.py collectstatic --noinput
            reload_server
