name: Python Lint Check

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main 
      - dev

jobs:
  lint:
    name: Run Python Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flake
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Run Flake
        run: flake8 .