name: Python Tests

on: 
  workflow_call:

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env: 
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run migrations
        env: 
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        working-directory: Plataforma_de_Vendas
        run: |
          python manage.py migrate

      - name: Run tests with coverage
        working-directory: Plataforma_de_Vendas 
        run: |
          pytest --cov=Accounts --cov=Products --cov=Orders --cov=Stores --cov-report=html

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Plataforma_de_Vendas/htmlcov/
          if-no-files-found: error


    
      

    

