name: Python Black Formatting Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  format:
    name: Run Black Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black Check
        run: black --check .

      