name: Python isort Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  isort:
    name: Run Python isort Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      
      - name: Install isort
        run: |
          python -m pip install --upgrade pip
          pip install isort
      
      - name: Run isort
        run: isort --check-only --diff .